import type { Metadata } from 'next'
import Navbar from './Layout/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './Layout/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home | Josh Dale',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-primary-black'>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}

// import dynamic from 'next/dynamic'
// import {draftMode} from 'next/headers'
// import { token } from '@/lib/sanity.fetch'

// const PreviewProvider = dynamic(() => import('./Components/PreviewProvider'))

// export default async function RootLayout({children}: {children: React.ReactNode}) {
//   return (
//     <html lang="en">
//       <body>
//       <Navbar />
//         {draftMode().isEnabled ? (
//           <PreviewProvider token={token}>{children}</PreviewProvider>
//         ) : (
//           children
//         )}
//         <Footer />
//       </body>
//     </html>
//   )
// }