import type { Metadata } from 'next'
import Navbar from './Layout/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './Layout/Footer'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home | Josh Dale',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}