export const safelist = [
    ' ',
   'border',
   'border-red-500',
   'flex',
   'justify-center',
   'justify-between',
   'grid',
   'gap-2',
   'gap-4',
   'text-white',
   'prose-p:text-red',
   'text-center',
   'w-full',
   'py-4',
   'py-8',
   'px-4',
   'px-8',
];